# Generated by Django 4.1.2 on 2022-10-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="isAccident",
            field=models.BooleanField(default=False),
        ),
    ]
