# Generated by Django 4.1.2 on 2022-11-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accident", "0003_post_predicted"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="content",),
    ]
